image: docker.phonepe.com:5000/pp-maven:3.8.4-openjdk-all

.default: &default
  only:
    - merge_requests
    - web

.default_tag: &default_tag
  tags:
    - backend-docker-large

stages:
  - build
  - quality
  - deploy
  - merge
  - release

build_package:
  stage: build
  <<: *default
  <<: *default_tag
  when: manual
  allow_failure: false
  script:
    - mvn clean package -U -DskipTests=true

merge_ready:
  stage: quality
  only:
    - merge_requests
  <<: *default_tag
  script:
    - mvn clean verify -U sonar:sonar -Pquality_check -Dsonar.pullrequest.key=$CI_MERGE_REQUEST_IID -Dsonar.pullrequest.branch=$CI_MERGE_REQUEST_SOURCE_BRANCH_NAME -Dsonar.pullrequest.base=$CI_MERGE_REQUEST_TARGET_BRANCH_NAME
  allow_failure: false

deploy_snapshot:
  stage: deploy
  <<: *default_tag
  <<: *default
  only:
    - web
  allow_failure: false
  script:
    - mvn deploy -DskipTests=true -Pdocker -Dmaven.install.skip=true
  when: manual

release:
  <<: *default_tag
  stage: release
  script:
    - git remote set-url origin "git@gitlab.phonepe.com:${CI_PROJECT_PATH}.git"
    - git checkout main
    - git pull origin main
    - git checkout develop
    - git pull origin develop
    - mvn -U jgitflow:release-start jgitflow:release-finish
    - git push --all
    - git push --tags origin
  when: manual
  only:
    refs:
      - develop